-- RenameIndex
ALTER INDEX "SellerDocumentAccessAudits_SellerVerificationDocumentID_Created" RENAME TO "SellerDocumentAccessAudits_SellerVerificationDocumentID_Cre_idx";

-- RenameIndex
ALTER INDEX "SellerVerificationDocuments_SellerVerificationProfileID_Documen" RENAME TO "SellerVerificationDocuments_SellerVerificationProfileID_Doc_idx";

-- RenameIndex
ALTER INDEX "SellerVerificationHistories_SellerVerificationProfileID_Created" RENAME TO "SellerVerificationHistories_SellerVerificationProfileID_Cre_idx";

-- RenameIndex
ALTER INDEX "SellerVerificationReviews_SellerVerificationProfileID_CreatedAt" RENAME TO "SellerVerificationReviews_SellerVerificationProfileID_Creat_idx";
