import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { FolderPlus, Pencil, Trash2 } from 'lucide-react';
import { useState } from 'react';
import { Alert } from '@/components/ui/Alert';
import { ManagementSearch } from '@/components/data-display/ManagementSearch';
import { Button } from '@/components/ui/Button';
import { Modal } from '@/components/ui/Modal';
import { SelectInput } from '@/components/ui/SelectInput';
import { Skeleton } from '@/components/ui/Skeleton';
import { TextInput } from '@/components/ui/TextInput';
import { Textarea } from '@/components/ui/Textarea';
import { sellerProductsApi } from '@/features/seller/api';
import { getErrorMessage } from '@/services/errors';
import { useToastStore } from '@/stores/toast.store';
import { sellerShopCategoriesApi } from '../seller-api';
import type { SellerShopCategory, ShopCategoryBody } from '../seller-api';

const emptyForm: ShopCategoryBody = { categoryName: '', description: '', sortOrder: 0, isActive: true };

export function SellerShopCategoriesPage() {
  const queryClient = useQueryClient(); const pushToast = useToastStore((state) => state.pushToast);
  const [editing, setEditing] = useState<SellerShopCategory | null>(null); const [isOpen, setIsOpen] = useState(false); const [form, setForm] = useState<ShopCategoryBody>(emptyForm); const [selectedProducts, setSelectedProducts] = useState<string[]>([]);  const [deleteTarget, setDeleteTarget] = useState<SellerShopCategory | null>(null); const [search, setSearch] = useState('');
  const categoriesQuery = useQuery({ queryKey: ['seller', 'shop-categories'], queryFn: sellerShopCategoriesApi.list });
  const productsQuery = useQuery({ queryKey: ['seller-products', 'shop-categories'], queryFn: () => sellerProductsApi.list(1, 100), enabled: isOpen });
  const categories = categoriesQuery.data ?? []; const products = productsQuery.data?.items ?? [];
  const normalizedSearch = search.trim().toLocaleLowerCase('vi');
  const filteredCategories = categories.filter((item) => `${item.categoryName} ${item.slug} ${item.description ?? ''} ${item.isActive ? 'đang hiển thị' : 'đang ẩn'}`.toLocaleLowerCase('vi').includes(normalizedSearch));
  const close = () => { setIsOpen(false); setEditing(null); setForm(emptyForm); setSelectedProducts([]); };
  const invalidate = () => queryClient.invalidateQueries({ queryKey: ['seller', 'shop-categories'] });
  const saveMutation = useMutation({ mutationFn: async () => { const category = editing ? await sellerShopCategoriesApi.update(editing.id, form) : await sellerShopCategoriesApi.create(form); await sellerShopCategoriesApi.assignProducts(category.id, selectedProducts); }, onSuccess: async () => { await invalidate(); pushToast({ tone: 'success', title: editing ? 'Đã cập nhật danh mục' : 'Đã tạo danh mục' }); close(); } });
  const deleteMutation = useMutation({ mutationFn: (id: string) => sellerShopCategoriesApi.remove(id), onSuccess: async () => { await invalidate(); setDeleteTarget(null); pushToast({ tone: 'success', title: 'Đã xóa danh mục' }); } });
  const openCreate = () => { setEditing(null); setForm(emptyForm); setSelectedProducts([]); setIsOpen(true); };
  const openEdit = (item: SellerShopCategory) => { setEditing(item); setForm({ categoryName: item.categoryName, parentShopCategoryId: item.parentShopCategoryId ?? undefined, description: item.description ?? '', sortOrder: item.sortOrder, isActive: item.isActive }); setSelectedProducts(item.productIds); setIsOpen(true); };

  return <div className="space-y-5">
    <section className="rounded-lg border border-border bg-white p-6 shadow-panel"><div className="flex flex-col gap-4 sm:flex-row sm:items-start sm:justify-between"><div><p className="text-xs font-semibold uppercase tracking-wide text-primary-700">Gian hàng</p><h1 className="mt-2 text-2xl font-semibold text-ink">Danh mục của gian hàng</h1><p className="mt-2 max-w-2xl text-sm text-muted">Tổ chức sản phẩm theo nhóm riêng để khách dễ khám phá và áp dụng voucher theo đúng danh mục của gian hàng.</p></div><Button type="button" onClick={openCreate}><FolderPlus size={17} aria-hidden="true"/>Tạo danh mục</Button></div></section>
    <ManagementSearch scope="shop-category" value={search} onChange={setSearch} placeholder="Tìm tên danh mục, slug hoặc trạng thái" resultCount={filteredCategories.length}/>
    {categoriesQuery.isError ? <Alert tone="danger">{getErrorMessage(categoriesQuery.error)}</Alert> : null}
    {categoriesQuery.isLoading ? <div className="space-y-3">{Array.from({ length: 4 }).map((_, index) => <Skeleton key={index} className="h-20"/>)}</div> : filteredCategories.length === 0 ? <section className="rounded-lg border border-dashed border-border bg-white p-10 text-center"><FolderPlus className="mx-auto text-muted"/><h2 className="mt-3 font-semibold">{search ? 'Không tìm thấy danh mục' : 'Chưa có danh mục riêng'}</h2><p className="mt-1 text-sm text-muted">{search ? 'Hãy thử từ khóa khác hoặc xóa nội dung tìm kiếm.' : 'Tạo danh mục đầu tiên và chọn những sản phẩm thuộc nhóm đó.'}</p>{!search ? <Button className="mt-4" onClick={openCreate}>Tạo danh mục</Button> : null}</section> : <section className="grid gap-3">{filteredCategories.map((item) => <article key={item.id} className="flex flex-col gap-3 rounded-lg border border-border bg-white p-4 shadow-panel sm:flex-row sm:items-center sm:justify-between"><div><div className="flex flex-wrap items-center gap-2"><h2 className="font-semibold text-ink">{item.categoryName}</h2><span className={`rounded-full px-2 py-1 text-xs ${item.isActive ? 'bg-success-soft text-success' : 'bg-surface text-muted'}`}>{item.isActive ? 'Đang hiển thị' : 'Đang ẩn'}</span></div><p className="mt-1 text-sm text-muted">{item.productIds.length} sản phẩm · /{item.slug}</p>{item.description ? <p className="mt-1 text-sm text-muted">{item.description}</p> : null}</div><div className="flex gap-2"><Button variant="secondary" onClick={() => openEdit(item)} aria-label={`Sửa danh mục ${item.categoryName}`}><Pencil size={16}/><span>Sửa</span></Button><Button variant="secondary" onClick={() => setDeleteTarget(item)} aria-label={`Xóa danh mục ${item.categoryName}`}><Trash2 size={16}/><span>Xóa</span></Button></div></article>)}</section>}
    <Modal open={isOpen} onClose={close} title={editing ? 'Chỉnh sửa danh mục' : 'Tạo danh mục mới'}><form className="space-y-4" onSubmit={(event) => { event.preventDefault(); if (form.categoryName.trim()) saveMutation.mutate(); }}><TextInput id="shop-category-name" label="Tên danh mục" required maxLength={150} value={form.categoryName} onChange={(event) => setForm({ ...form, categoryName: event.target.value })}/><SelectInput id="shop-category-parent" label="Danh mục cha" value={form.parentShopCategoryId ?? ''} onChange={(event) => setForm({ ...form, parentShopCategoryId: event.target.value || undefined })}><option value="">Không có danh mục cha</option>{categories.filter((item) => item.id !== editing?.id).map((item) => <option key={item.id} value={item.id}>{item.categoryName}</option>)}</SelectInput><Textarea id="shop-category-description" label="Mô tả" maxLength={500} value={form.description ?? ''} onChange={(event) => setForm({ ...form, description: event.target.value })}/><TextInput id="shop-category-sort" label="Thứ tự hiển thị" type="number" min={0} value={form.sortOrder ?? 0} onChange={(event) => setForm({ ...form, sortOrder: Number(event.target.value) })}/><label className="flex min-h-11 items-center gap-3"><input type="checkbox" className="h-5 w-5 accent-primary-600" checked={form.isActive ?? true} onChange={(event) => setForm({ ...form, isActive: event.target.checked })}/><span className="text-sm font-medium">Hiển thị trên trang gian hàng</span></label><fieldset className="rounded-lg border border-border p-3"><legend className="px-1 text-sm font-medium">Sản phẩm trong danh mục</legend>{productsQuery.isLoading ? <Skeleton className="mt-2 h-32"/> : products.length === 0 ? <p className="py-4 text-sm text-muted">Gian hàng chưa có sản phẩm.</p> : <div className="mt-2 max-h-56 space-y-1 overflow-y-auto">{products.map((product) => <label key={product.id} className="flex min-h-11 items-center gap-3 rounded-md px-2 hover:bg-surface"><input type="checkbox" className="h-5 w-5 accent-primary-600" checked={selectedProducts.includes(product.id)} onChange={(event) => setSelectedProducts((current) => event.target.checked ? [...current, product.id] : current.filter((id) => id !== product.id))}/><span className="text-sm">{product.productName}</span></label>)}</div>}</fieldset>{saveMutation.isError ? <Alert tone="danger">{getErrorMessage(saveMutation.error)}</Alert> : null}<div className="flex justify-end gap-2"><Button type="button" variant="secondary" onClick={close}>Hủy</Button><Button type="submit" disabled={saveMutation.isPending || !form.categoryName.trim()}>{saveMutation.isPending ? 'Đang lưu...' : 'Lưu danh mục'}</Button></div></form></Modal>
    <Modal open={Boolean(deleteTarget)} onClose={() => setDeleteTarget(null)} title="Xóa danh mục"><div className="flex justify-end gap-2"><Button variant="secondary" onClick={() => setDeleteTarget(null)}>Hủy</Button><Button disabled={deleteMutation.isPending} onClick={() => deleteTarget && deleteMutation.mutate(deleteTarget.id)}>{deleteMutation.isPending ? 'Đang xóa...' : 'Xóa danh mục'}</Button></div></Modal>
  </div>;
}
