export type ShopResponse = {
  id: string;
  idString: string;
  ownerUserId: string;
  ownerUserIdString: string;
  shopName: string;
  slug: string;
  description: string | null;
  email: string | null;
  phoneNumber: string | null;
  province: string | null;
  ward: string | null;
  streetAddress: string | null;
  avatarUrl: string | null;
  taxCode: string | null;
  shopStatus: string;
  operationMode: 'Open' | 'PausedUntil' | 'PausedIndefinitely';
  pauseStartsAt: Date | null;
  pauseEndsAt: Date | null;
  pauseReason: string | null;
  operationUpdatedAt: Date | null;
  isAcceptingOrders: boolean;
  approvedByUserId: string | null;
  approvedByUserIdString: string | null;
  approvedAt: Date | null;
  rejectionReason: string | null;
  isDeleted: boolean;
  createdAt: Date;
  updatedAt: Date | null;
};
